parameters:
#    s2n_show.example.class: S2n\ShowBundle\Example

services:
#    s2n_show.example:
#        class: %s2n_show.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
